version: '3.9'

services:
  faculty:
    build: ./FacultyService
    container_name: faculty-service
    ports:
      - "5001:5000"   
    networks:
      - mynetwork

  department:
    build: ./DepartmentService
    container_name: department-service
    ports:
      - "5002:5000"
    networks:
      - mynetwork

  gateway:
    image: nginx:alpine
    container_name: api-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - faculty
      - department
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
